name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Update to the latest version of checkout

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1  # AWS credentials configuration action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Copy site content to the S3 bucket
        run: aws s3 sync . s3://amitkumar0441githubactionbucket --delete
